const shared = {
  en: {
    back: "Back to selected work",
    factLabels: {
      role: "Role",
      type: "Type",
      environment: "Environment",
      tools: "Tools",
      status: "Status",
      delivered: "Evidence",
    },
    snapshotLabels: {
      problem: "Reported issue",
      user: "User impact",
      result: "Lab result",
    },
    sectionLabels: {
      snapshot: "Brief",
      context: "Incident",
      investigation: "Investigation",
      resolution: "Resolution",
      prevention: "Prevention",
      outcome: "Evidence",
    },
    headings: {
      ticket: "The ticket, before troubleshooting",
      scope: "Environment and boundaries",
      trail: "Evidence trail",
      decisions: "Diagnostic decisions",
      artifact: "Technical record",
      validation: "Validation checks",
      communication: "User-facing update",
      escalation: "Escalation threshold",
      runbook: "Reusable runbook",
      measures: "What a production team should measure",
      proof: "What this case demonstrates",
      limits: "Limits and disclosure",
      references: "Technical references",
    },
    artifactLabels: {
      field: "Field",
      observed: "Observed",
      meaning: "Meaning",
    },
    common: {
      synthetic: "Synthetic data",
      resolved: "Resolved in simulation",
      validated: "Validated",
      expected: "Expected",
      observed: "Observed",
      download: "Discuss this case",
    },
  },
  fr: {
    back: "Retour aux projets sélectionnés",
    factLabels: {
      role: "Rôle",
      type: "Type",
      environment: "Environnement",
      tools: "Outils",
      status: "Statut",
      delivered: "Preuves",
    },
    snapshotLabels: {
      problem: "Incident signalé",
      user: "Impact utilisateur",
      result: "Résultat du labo",
    },
    sectionLabels: {
      snapshot: "Résumé",
      context: "Incident",
      investigation: "Enquête",
      resolution: "Résolution",
      prevention: "Prévention",
      outcome: "Preuves",
    },
    headings: {
      ticket: "Le billet, avant le dépannage",
      scope: "Environnement et limites",
      trail: "Parcours des preuves",
      decisions: "Décisions diagnostiques",
      artifact: "Dossier technique",
      validation: "Contrôles de validation",
      communication: "Mise à jour destinée à l’utilisateur",
      escalation: "Seuil de transmission",
      runbook: "Procédure réutilisable",
      measures: "Ce qu’une équipe de production devrait mesurer",
      proof: "Ce que ce cas démontre",
      limits: "Limites et divulgation",
      references: "Références techniques",
    },
    artifactLabels: {
      field: "Champ",
      observed: "Observation",
      meaning: "Interprétation",
    },
    common: {
      synthetic: "Données synthétiques",
      resolved: "Résolu en simulation",
      validated: "Validé",
      expected: "Attendu",
      observed: "Observé",
      download: "Discuter de ce cas",
    },
  },
};

const en = {
  "access-restored": {
    slug: "access-restored",
    kind: "access",
    year: "2026",
    tag: "Independent IT support simulation",
    plainTitle: "Access Restored",
    title: "Access *Restored*",
    subtitle: "Windows 11 & Microsoft 365 access support lab",
    lead: "A time-sensitive sign-in failure is isolated across the user, device, application and network layers—without resetting credentials blindly or claiming tenant-level access.",
    facts: {
      role: "L1 service desk analyst · simulated",
      type: "Scenario-based troubleshooting lab",
      environment: "Windows 11 Pro VM · Microsoft 365 sign-in path",
      tools: "PowerShell · Windows Time · Event Viewer · ticket record",
      status: "Documented simulation · no live Microsoft tenant",
      delivered: "Ticket · command record · validation · user update · escalation note",
    },
    snapshot: {
      problem: "After a password change, Outlook and Teams repeatedly requested sign-in while Windows still opened with cached credentials.",
      user: "One remote employee could open the device but could not access the communication tools required for the morning shift.",
      result: "An 8-minute device clock drift was isolated and corrected; the authentication path then passed all simulated validation checks.",
    },
    preview: {
      url: "support.test/incidents/INC-1047",
      eyebrow: "Access investigation",
      id: "INC-1047",
      status: "Resolved",
      headline: "Microsoft 365 sign-in loop",
      detail: "One user · Windows 11 · remote",
      nodes: [
        { label: "User", value: "Password changed", state: "clear" },
        { label: "Device", value: "+08:14 drift", state: "fault" },
        { label: "Application", value: "Token rejected", state: "review" },
        { label: "Network", value: "TCP 443 reachable", state: "clear" },
      ],
    },
    context: {
      number: "01 — Incident & scope",
      heading: "A sign-in prompt can originate far beyond the password.",
      prose: [
        "The report arrived at 08:17 after the user changed a password the previous evening. Windows 11 still opened, but Outlook and Teams requested authentication repeatedly. A colleague on the same service was unaffected.",
        "The support objective was to restore access with the least invasive safe action. The investigation therefore separated account, device, application, connectivity and service health instead of treating every authentication symptom as a password problem.",
      ],
      ticket: {
        id: "INC-1047",
        status: "High · single user",
        title: "Outlook and Teams return to sign-in after password change",
        tags: ["Windows 11", "Microsoft 365", "Remote", "Identity"],
        fields: [
          ["Received", "08:17 CET"],
          ["Channel", "Service portal"],
          ["Affected", "1 user / 1 device"],
          ["Business impact", "Morning communications blocked"],
          ["Last known good", "Previous day · 17:40"],
          ["Recent change", "Password updated"],
        ],
      },
      scope: [
        { term: "Controlled evidence", desc: "Windows-side checks, command output, timing and the ticket history are represented with synthetic lab data." },
        { term: "No tenant administration", desc: "No Entra ID, Conditional Access, licence or Intune policy was changed. Those checks remain explicit escalation paths." },
        { term: "Security boundary", desc: "The workflow never asks the user to disclose a password, approve an unexpected MFA prompt or disable security controls." },
      ],
    },
    investigation: {
      number: "02 — Investigation",
      heading: "Test the path in layers; change one variable at a time.",
      prose: [
        "The evidence ruled out a broad Microsoft 365 outage and basic reachability before any credential action. Comparing device time with a trusted time source exposed the first abnormal condition.",
        "Windows Time was running, but the restored VM snapshot had not resynchronized. Authentication tokens are time-bound, so the device clock became the strongest local hypothesis.",
      ],
      trail: [
        { time: "08:20", title: "Confirmed scope", evidence: "One user and one Windows 11 device; colleague unaffected.", result: "Treat as local or account-specific, not a broad outage.", state: "clear" },
        { time: "08:24", title: "Checked service and network", evidence: "Microsoft 365 service path assumed available; TCP 443 to login.microsoftonline.com succeeded.", result: "Basic reachability was not the failure point.", state: "clear" },
        { time: "08:29", title: "Compared device time", evidence: "Device clock was 8 minutes 14 seconds ahead of the trusted reference.", result: "Time drift can invalidate token-based authentication.", state: "fault" },
        { time: "08:33", title: "Resynchronized safely", evidence: "Windows Time status checked, then a resync was requested without clearing profiles or credentials.", result: "Clock returned within one second of reference.", state: "clear" },
        { time: "08:38", title: "Validated access", evidence: "Browser sign-in, Outlook and Teams completed the simulated checks with no repeated prompt.", result: "User workflow restored; ticket ready to close.", state: "clear" },
      ],
      artifact: {
        eyebrow: "PowerShell record · synthetic lab output",
        title: "A small command set tied to explicit questions",
        note: "The commands show what each check was meant to establish. Output is synthetic and does not expose a real user, tenant or device.",
        code: `PS> Get-Date\nTuesday, September 22, 2026 08:29:14\n\nPS> Get-Service W32Time\nStatus   Name      DisplayName\nRunning  W32Time   Windows Time\n\nPS> w32tm /query /status\nSource: Local CMOS Clock\nLast Successful Sync Time: 9/21/2026 5:42:03 PM\n\nPS> Test-NetConnection login.microsoftonline.com -Port 443\nTcpTestSucceeded : True\n\nPS> w32tm /resync\nThe command completed successfully.`,
        rows: [
          ["Clock offset", "+00:08:14", "Outside the expected authentication tolerance; investigate time sync."],
          ["Windows Time", "Running", "The service exists, but its source and last successful sync still matter."],
          ["TCP 443", "Reachable", "The sign-in endpoint is reachable; this does not prove credentials are valid."],
          ["User scope", "1 of 1 device", "Keep the investigation local until evidence shows broader impact."],
        ],
      },
      decisions: [
        { name: "Do not reset the password twice", problem: "A recent password change makes another reset tempting, but it can add lockouts and cached-credential confusion.", decision: "Verify scope, time, connectivity and the browser path before changing identity data.", tradeoff: "A few more diagnostic minutes in exchange for avoiding an unnecessary security-sensitive action." },
        { name: "Use the browser as an isolation step", problem: "Desktop clients contain caches, profiles and plug-ins that can obscure the authentication path.", decision: "Compare browser sign-in with Outlook and Teams after network and time checks.", tradeoff: "It does not fix the desktop clients, but it separates account access from local application state." },
        { name: "Escalate policy, licence and compliance evidence", problem: "L1 support should not guess at Conditional Access, licensing or managed-device policy.", decision: "Attach timestamps, user impact and completed local checks for the Microsoft 365 or identity administrator.", tradeoff: "Resolution may require another owner, but the handoff arrives actionable and auditable." },
      ],
    },
    resolution: {
      number: "03 — Resolution & validation",
      heading: "Restore the trusted time source, then prove the user can work.",
      prose: [
        "The simulated corrective action resynchronized Windows Time. No profile was deleted, no password was exposed and no security policy was bypassed.",
        "Closure required more than a successful command: the validation sequence checked time, browser authentication and both affected applications in the order the user needed them.",
      ],
      validation: [
        ["Clock difference", "Under 1 second", "done"],
        ["Browser sign-in", "Completed", "done"],
        ["Outlook", "Mailbox opened", "done"],
        ["Teams", "Session connected", "done"],
      ],
      communication: {
        label: "Resolution update · 08:40 CET",
        text: "Access is restored. The device clock was out of sync, which interrupted Microsoft 365 authentication. I resynchronized Windows Time and verified browser sign-in, Outlook and Teams with you. No further password change was required. Please reopen the ticket if the sign-in prompt returns.",
      },
      escalation: "Escalate with the sign-in timestamp, user principal name, device identifier and completed local checks if MFA registration, licence assignment, Conditional Access, Entra sign-in logs or Intune compliance remain suspected. Never request screenshots that expose tokens, passwords or recovery codes.",
    },
    prevention: {
      number: "04 — Prevention & reuse",
      heading: "Turn one resolution into a safer first-response pattern.",
      prose: [
        "The reusable output is a short access runbook that begins with impact and scope, then moves from low-risk observation to account-level escalation.",
        "In a managed environment, recurring time drift should be treated as an endpoint-management signal rather than repeatedly corrected one device at a time.",
      ],
      runbook: [
        "Confirm affected user, device, applications, exact error and recent changes.",
        "Check service health and whether another user or device is affected.",
        "Verify local date, time, time zone, Windows Time source and network reachability.",
        "Compare browser and desktop-client behaviour without deleting profiles prematurely.",
        "Resolve within scope or escalate identity, licence and compliance evidence to the correct owner.",
        "Validate the user’s real workflow and document cause, action and next step.",
      ],
      measures: [
        ["Repeat sign-in incidents by root cause", "Shows whether time, client cache, MFA or policy deserves a permanent fix."],
        ["First-contact resolution for access tickets", "Shows whether L1 runbooks restore access without unsafe shortcuts."],
        ["Reopen rate within seven days", "Shows whether validation reflected the user’s actual workflow."],
      ],
    },
    outcome: {
      number: "05 — Evidence & limits",
      heading: "A complete support record, not a claim of production administration.",
      prose: [
        "This case demonstrates structured L1 investigation, security-aware communication and evidence-based escalation. It does not claim Microsoft tenant ownership or a measured business result.",
      ],
      proof: [
        ["Troubleshooting", "Separated identity, device, application, network and service layers."],
        ["Technical communication", "Converted command evidence into a concise user update and closure note."],
        ["Operational judgement", "Used the least invasive safe action and defined when another team must own the next step."],
      ],
      limits: [
        "Scenario, timestamps, names and outputs are synthetic.",
        "No live Microsoft 365 tenant, Entra ID directory or Intune policy was accessed.",
        "The simulated result is not presented as customer, SLA or production performance.",
      ],
      references: [
        ["Microsoft Learn · Windows Time service tools and settings", "https://learn.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings"],
        ["Microsoft Learn · Test-NetConnection", "https://learn.microsoft.com/en-us/powershell/module/nettcpip/test-netconnection"],
        ["IETF RFC 7519 · JSON Web Token time claims", "https://www.rfc-editor.org/rfc/rfc7519.html"],
      ],
    },
  },

  "missing-reservation": {
    slug: "missing-reservation",
    kind: "application",
    year: "2026",
    tag: "Independent application support simulation",
    plainTitle: "The Missing Reservation",
    title: "The Missing *Reservation*",
    subtitle: "SaaS application support — API, webhook, logs & SQL",
    lead: "A reservation accepted by one API never appears downstream. One correlation ID connects the customer report to the payload, webhook failure, read-only SQL check and engineering-ready resolution.",
    facts: {
      role: "Junior application support analyst · simulated",
      type: "Synthetic integration incident",
      environment: "Mock reservation API · webhook consumer · relational event store",
      tools: "Postman-style request · HTTP/JSON · SQL · logs · Jira-ready handoff",
      status: "Reproducible scenario · no client or production data",
      delivered: "Ticket · payload · log trace · SQL check · replay validation · KB note",
    },
    snapshot: {
      problem: "The source platform returned 202 Accepted, but reservation RSV-8F31C never appeared in the partner dashboard.",
      user: "An operations agent could not confirm whether a guest arrival had reached the downstream property system.",
      result: "A locale-formatted date caused a 422 webhook rejection; the corrected event replayed once and produced one downstream record.",
    },
    preview: {
      url: "support.test/cases/APP-2318",
      eyebrow: "Integration trace",
      id: "APP-2318",
      status: "Resolved",
      headline: "Reservation accepted, not delivered",
      detail: "Correlation · req_9c7f2a",
      nodes: [
        { label: "API", value: "202 accepted", state: "clear" },
        { label: "Queue", value: "evt_7a31", state: "clear" },
        { label: "Webhook", value: "422 date format", state: "fault" },
        { label: "Database", value: "1 row after replay", state: "clear" },
      ],
    },
    context: {
      number: "01 — Incident & scope",
      heading: "Accepted is not the same as delivered.",
      prose: [
        "At 14:06, an operations agent reported that a confirmed reservation was visible in the source platform but absent from a downstream partner dashboard. Re-entering it manually could create a duplicate, so the first task was to establish the event state before changing data.",
        "The scenario uses a fictional reservation flow inspired by common service operations. Every customer, identifier, payload and log line is synthetic; no ICNEA, Salesforce, hotel or guest data is represented.",
      ],
      ticket: {
        id: "APP-2318",
        status: "High · arrival today",
        title: "Confirmed reservation missing from partner dashboard",
        tags: ["SaaS", "REST API", "Webhook", "SQL"],
        fields: [
          ["Received", "14:06 CET"],
          ["Reservation", "RSV-8F31C"],
          ["Correlation ID", "req_9c7f2a"],
          ["Event ID", "evt_7a31"],
          ["Source response", "202 Accepted"],
          ["Business impact", "Arrival cannot be confirmed downstream"],
        ],
      },
      scope: [
        { term: "Read before write", desc: "The investigation checks event and reservation state before any replay or manual correction." },
        { term: "Synthetic integration", desc: "The API, webhook consumer, database rows and logs form one internally consistent fictional environment." },
        { term: "Support boundary", desc: "Application Support validates and packages the defect; a production code or mapping change would remain Engineering-owned." },
      ],
    },
    investigation: {
      number: "02 — Investigation",
      heading: "Follow one correlation ID across every handoff.",
      prose: [
        "The 202 response proved only that the source accepted work for asynchronous processing. Searching by correlation ID connected the request to event evt_7a31 and a downstream 422 response.",
        "The webhook expected an ISO 8601 calendar date. The outgoing payload contained a Spanish locale format, 23/09/2026. A read-only SQL query confirmed that the event failed three times and no downstream reservation row existed.",
      ],
      trail: [
        { time: "14:09", title: "Protected against duplication", evidence: "No manual re-entry; reservation ID and correlation ID captured first.", result: "Preserve idempotency while the delivery state is unknown.", state: "clear" },
        { time: "14:13", title: "Verified source acceptance", evidence: "POST returned 202 with req_9c7f2a and event evt_7a31.", result: "Request entered the asynchronous path; delivery still unproven.", state: "clear" },
        { time: "14:18", title: "Traced webhook failure", evidence: "Consumer returned HTTP 422: check_in must use YYYY-MM-DD.", result: "Payload validation stopped downstream creation.", state: "fault" },
        { time: "14:23", title: "Checked stored state", evidence: "integration_events showed failed / retry_count 3; reservations returned zero rows.", result: "Safe to prepare one controlled replay after correction.", state: "clear" },
        { time: "14:31", title: "Replayed and validated", evidence: "Corrected payload returned 200 processed; a second idempotent replay did not create another row.", result: "Delivery restored with exactly one reservation record.", state: "clear" },
      ],
      artifact: {
        eyebrow: "HTTP, JSON and SQL · synthetic records",
        title: "The failure is visible in the contract and the stored state",
        note: "Identifiers are fictional. The query is read-only and limits the search to the reservation and event involved in the ticket.",
        code: `// outbound webhook · evt_7a31\n{\n  "reservation_id": "RSV-8F31C",\n  "check_in": "23/09/2026",\n  "check_out": "2026-09-25",\n  "guest_count": 2\n}\n\nHTTP/1.1 422 Unprocessable Content\n{ "error": "check_in must use YYYY-MM-DD" }\n\nSELECT event_id, correlation_id, status, retry_count, last_http_status\nFROM integration_events\nWHERE event_id = 'evt_7a31';\n\n-- evt_7a31 | req_9c7f2a | failed | 3 | 422`,
        rows: [
          ["Source response", "202 Accepted", "The job was queued, not completed downstream."],
          ["check_in", "23/09/2026", "Locale-formatted date violates the consumer contract."],
          ["Webhook response", "422", "The consumer understood the request but rejected its data."],
          ["Reservation rows", "0 before / 1 after", "The controlled replay created one record and no duplicate."],
        ],
      },
      decisions: [
        { name: "Do not convert 202 into a success claim", problem: "An asynchronous API can accept work before a downstream operation succeeds.", decision: "Track the returned event and correlation identifiers through the queue, webhook and stored state.", tradeoff: "More investigation than reading the first response, but a defensible delivery conclusion." },
        { name: "Query only the incident slice", problem: "Broad database access increases risk and produces noisy evidence.", decision: "Use a read-only query scoped to the event and reservation identifiers in the ticket.", tradeoff: "Less exploratory context, but safer and easier to reproduce." },
        { name: "Replay with an idempotency check", problem: "Retrying a successful operation can create duplicate reservations.", decision: "Confirm zero downstream rows, correct the payload, replay once and test the same event a second time for duplicate protection.", tradeoff: "Additional validation steps in exchange for data integrity." },
      ],
    },
    resolution: {
      number: "03 — Resolution & validation",
      heading: "Correct the contract mismatch, then validate state—not just HTTP.",
      prose: [
        "The lab correction changed check_in to 2026-09-23 and replayed evt_7a31 with the original idempotency key. The consumer returned 200 processed and the event state changed from failed to processed.",
        "A second replay returned the existing result and the database still contained one reservation. That final duplicate check closed the risk created by the earlier failed retries.",
      ],
      validation: [
        ["Webhook", "200 processed", "done"],
        ["Event status", "processed", "done"],
        ["Reservation rows", "exactly 1", "done"],
        ["Idempotent replay", "no duplicate", "done"],
      ],
      communication: {
        label: "Customer update · 14:34 CET",
        text: "The reservation reached the source system but failed during downstream validation because one date used a local display format instead of the integration format. The corrected event has now processed successfully, and I verified that exactly one reservation appears in the partner record. No manual re-entry is needed.",
      },
      escalation: "A production handoff would include the sanitized payload, expected schema, correlation and event IDs, UTC timestamps, 422 response, retry count, scoped SQL result, reproduction steps and impact. Engineering should own any permanent mapper or contract change; Support should own the customer thread through confirmation.",
    },
    prevention: {
      number: "04 — Prevention & reuse",
      heading: "Make the next format error fail earlier and explain itself better.",
      prose: [
        "The immediate fix restores one event. Prevention belongs in contract validation, mapping tests, actionable logs and a support runbook that distinguishes accepted, queued, delivered and failed states.",
        "A recurring 422 pattern should be summarized for Product and Engineering rather than normalized as manual support work.",
      ],
      runbook: [
        "Capture customer impact, business identifier, exact timestamp and the first system that shows the record.",
        "Record correlation, request and event identifiers before retrying or changing data.",
        "Separate transport success from downstream business processing.",
        "Inspect sanitized request/response payloads, logs and read-only stored state.",
        "Check idempotency and row state before one controlled replay.",
        "Validate the customer-visible result and escalate permanent contract changes with a complete evidence package.",
      ],
      measures: [
        ["Webhook failures by status and field", "Reveals whether one mapper, customer or contract creates repeat work."],
        ["Accepted-to-delivered latency", "Separates fast API acknowledgement from actual downstream availability."],
        ["Duplicate prevention on replay", "Confirms that recovery procedures protect data integrity."],
      ],
    },
    outcome: {
      number: "05 — Evidence & limits",
      heading: "Support reasoning between the customer and Engineering.",
      prose: [
        "This case demonstrates how junior Application Support can move from a customer report to a reproducible, evidence-backed handoff without pretending to own production code or customer data.",
      ],
      proof: [
        ["API reasoning", "Distinguished request acceptance from asynchronous delivery and interpreted a 422 response."],
        ["Data checks", "Used a scoped read-only query and verified exactly one resulting record."],
        ["Escalation quality", "Connected customer impact, payload, logs, identifiers, reproduction and expected behaviour."],
      ],
      limits: [
        "The company, systems, reservation, payloads, logs and timestamps are fictional.",
        "No ICNEA, Salesforce, hotel, guest or client data is used or implied.",
        "The scenario demonstrates investigation logic, not production API or database access."],
      references: [
        ["IETF RFC 9110 · 202 Accepted", "https://www.rfc-editor.org/rfc/rfc9110.html#name-202-accepted"],
        ["IETF RFC 9110 · 422 Unprocessable Content", "https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content"],
        ["IETF RFC 3339 · Date and time on the Internet", "https://www.rfc-editor.org/rfc/rfc3339.html"],
      ],
    },
  },

  "connectivity-broke": {
    slug: "connectivity-broke",
    kind: "network",
    year: "2026",
    tag: "Independent network support simulation",
    plainTitle: "Where Connectivity Broke",
    title: "Where Connectivity *Broke*",
    subtitle: "L1 network troubleshooting — TCP/IP, DNS & DHCP",
    lead: "Three Windows clients can reach the gateway and a public IP but not an internal service by name. Layered tests isolate a stale DNS address distributed through DHCP.",
    facts: {
      role: "L1 IT support analyst · simulated",
      type: "Scenario-based network troubleshooting lab",
      environment: "3 Windows clients · LAN/VLAN model · DHCP · internal DNS",
      tools: "ipconfig · ping · nslookup · tracert · Test-NetConnection",
      status: "Documented topology simulation · no production network",
      delivered: "Ticket · topology · command evidence · fix sequence · validation · runbook",
    },
    snapshot: {
      problem: "Users could reach the gateway and 1.1.1.1, but portal.supportlab.test failed by hostname on three DHCP clients.",
      user: "A reception team could not open an internal web portal while general IP connectivity remained available.",
      result: "DHCP option 6 pointed to a retired DNS server; clients renewed the corrected lease and name resolution returned.",
    },
    preview: {
      url: "support.test/network/NET-0732",
      eyebrow: "Connectivity path",
      id: "NET-0732",
      status: "Resolved",
      headline: "Hostname fails; IP path works",
      detail: "3 clients · VLAN 10",
      nodes: [
        { label: "Client", value: "192.168.10.42", state: "clear" },
        { label: "Gateway", value: "192.168.10.1", state: "clear" },
        { label: "DNS", value: "192.168.10.53", state: "fault" },
        { label: "Portal", value: "192.168.20.25:443", state: "review" },
      ],
    },
    context: {
      number: "01 — Incident & scope",
      heading: "“The network is down” is a symptom, not a diagnosis.",
      prose: [
        "At 09:12, reception reported that an internal portal would not open. Three Windows clients showed the same browser error, but other applications appeared normal. The scope suggested shared configuration rather than one damaged device.",
        "The diagnostic path tested local addressing, gateway reachability, external IP reachability, name resolution and the destination port separately. This kept DNS failure distinct from Wi-Fi, DHCP lease, routing and service availability.",
      ],
      ticket: {
        id: "NET-0732",
        status: "High · 3 users",
        title: "Internal portal unavailable by hostname on reception LAN",
        tags: ["Windows 11", "TCP/IP", "DNS", "DHCP"],
        fields: [
          ["Received", "09:12 CET"],
          ["Affected", "3 clients / VLAN 10"],
          ["Hostname", "portal.supportlab.test"],
          ["Client IP", "192.168.10.42/24"],
          ["Gateway", "192.168.10.1"],
          ["DHCP DNS", "192.168.10.53"],
        ],
      },
      scope: [
        { term: "Modeled topology", desc: "The addresses use private and reserved lab ranges. They do not identify a real home or business network." },
        { term: "One layer per test", desc: "Link, addressing, gateway, routing, DNS and application port are evaluated separately." },
        { term: "L1 change boundary", desc: "The simulation documents the DHCP correction. In production, changing scope options may belong to Network or Infrastructure." },
      ],
    },
    investigation: {
      number: "02 — Investigation",
      heading: "Prove what still works before fixing what does not.",
      prose: [
        "The client had a valid private address, subnet mask and gateway—so this was not APIPA or a missing DHCP lease. Successful pings to the gateway and 1.1.1.1 proved local and routed IP connectivity.",
        "nslookup timed out against 192.168.10.53. Comparing the DHCP scope with the current topology showed that option 6 still distributed a retired DNS server; the active resolver was 192.168.10.10.",
      ],
      trail: [
        { time: "09:15", title: "Confirmed shared scope", evidence: "Three DHCP clients on VLAN 10 failed on the same hostname.", result: "Prioritize shared DNS/DHCP configuration over a browser-only fault.", state: "clear" },
        { time: "09:18", title: "Verified addressing", evidence: "192.168.10.42/24, gateway 192.168.10.1; no 169.254.x.x address.", result: "Client received a usable lease.", state: "clear" },
        { time: "09:21", title: "Tested the IP path", evidence: "Gateway and 1.1.1.1 replied; route left the local subnet.", result: "Wi-Fi association and basic routing are available.", state: "clear" },
        { time: "09:24", title: "Isolated name resolution", evidence: "nslookup timed out against DHCP-provided DNS 192.168.10.53.", result: "Failure sits at DNS configuration or resolver availability.", state: "fault" },
        { time: "09:32", title: "Renewed and validated", evidence: "DHCP option corrected to 192.168.10.10; renewed clients resolved the portal and reached TCP 443.", result: "Shared access restored on all three clients.", state: "clear" },
      ],
      artifact: {
        eyebrow: "Windows network record · synthetic output",
        title: "Commands answer different questions",
        note: "The sequence avoids using ping as a universal network test. Each result narrows the failing layer.",
        code: `C:\\> ipconfig /all\nIPv4 Address . . . . . : 192.168.10.42\nDefault Gateway . . .  : 192.168.10.1\nDHCP Server . . . . .  : 192.168.10.1\nDNS Servers . . . . .  : 192.168.10.53\n\nC:\\> ping 192.168.10.1\nPackets: Sent = 4, Received = 4, Lost = 0 (0% loss)\n\nC:\\> ping 1.1.1.1\nPackets: Sent = 4, Received = 4, Lost = 0 (0% loss)\n\nC:\\> nslookup portal.supportlab.test\nDNS request timed out. Server: 192.168.10.53\n\nPS> Test-NetConnection 192.168.20.25 -Port 443\nTcpTestSucceeded : True`,
        rows: [
          ["DHCP lease", "Valid 192.168.10.42/24", "Addressing exists; do not diagnose APIPA."],
          ["Gateway", "4/4 replies", "The local path to the router works."],
          ["Public IP", "4/4 replies", "Routed IP connectivity works without DNS."],
          ["DNS server", "Timeout at 192.168.10.53", "The configured resolver is stale or unavailable."],
        ],
      },
      decisions: [
        { name: "Separate name resolution from connectivity", problem: "A browser error is often reported as total internet failure.", decision: "Compare gateway, public IP, hostname and destination-port tests before changing the adapter.", tradeoff: "A longer evidence sequence, but fewer disruptive resets and a precise fault domain." },
        { name: "Treat three clients as shared evidence", problem: "Repeating local fixes on each device hides a DHCP or infrastructure fault.", decision: "Compare lease data across affected clients and inspect the common scope settings.", tradeoff: "Requires coordination with the network owner, but fixes the source rather than each symptom." },
        { name: "Renew after correcting the source", problem: "Changing DHCP option 6 does not update an active client lease immediately.", decision: "Release and renew the lease, flush the resolver cache and rerun the same validation tests.", tradeoff: "A brief client interruption in exchange for proving that the corrected configuration was received." },
      ],
    },
    resolution: {
      number: "03 — Resolution & validation",
      heading: "Correct the shared DNS setting, then repeat the original path.",
      prose: [
        "The modeled DHCP scope was updated from retired resolver 192.168.10.53 to active resolver 192.168.10.10. Clients then renewed their leases and cleared the local resolver cache.",
        "Validation repeated the same layers used during diagnosis. All three clients received the correct DNS address, resolved the internal hostname to 192.168.20.25 and reached the portal on TCP 443.",
      ],
      validation: [
        ["DHCP option 6", "192.168.10.10", "done"],
        ["Name resolution", "192.168.20.25", "done"],
        ["Portal TCP 443", "reachable", "done"],
        ["Affected clients", "3 of 3 restored", "done"],
      ],
      communication: {
        label: "Resolution update · 09:35 CET",
        text: "Access to the internal portal is restored on all three reception computers. The devices had valid network connectivity, but DHCP was providing an old DNS server address. The shared setting was corrected, the client leases were renewed and the hostname and secure port were validated. No action is required from the users.",
      },
      escalation: "Escalate if the active resolver itself is unavailable, multiple VLANs are affected, the DHCP scope cannot be changed within L1 permissions, packet loss appears beyond the gateway, or the hostname resolves correctly while the service port remains closed. Include affected scope, lease data, timestamps, command results and topology segment.",
    },
    prevention: {
      number: "04 — Prevention & reuse",
      heading: "Keep shared configuration changes from becoming user-discovered incidents.",
      prose: [
        "The runbook turns a vague connectivity report into a repeatable decision path. The preventive action is to include DHCP option review and client renewal in DNS server retirement plans.",
        "A small synthetic resolution check from each important VLAN would detect a stale resolver before users report that applications have disappeared.",
      ],
      runbook: [
        "Confirm number of users, network segment, connection type, exact hostname and recent infrastructure changes.",
        "Check link and lease: IP address, subnet, gateway, DHCP server and DNS servers.",
        "Test local gateway, routed IP, DNS resolution and destination port separately.",
        "Compare affected clients to locate shared DHCP, DNS or VLAN configuration.",
        "Correct within authority or escalate with the failing layer and evidence.",
        "Renew the lease, flush cache, repeat tests and validate the user’s application.",
      ],
      measures: [
        ["DNS resolution success by VLAN", "Detects shared resolver failures before they become repeated tickets."],
        ["Lease renewals after scope changes", "Shows whether clients actually received the new configuration."],
        ["Connectivity incidents by failing layer", "Separates Wi-Fi, DHCP, DNS, routing and service problems for prevention."],
      ],
    },
    outcome: {
      number: "05 — Evidence & limits",
      heading: "Network fundamentals applied as support evidence.",
      prose: [
        "This case demonstrates operational TCP/IP, DHCP and DNS reasoning at L1 depth: enough to isolate the break, restore within scope or hand the correct evidence to Infrastructure.",
      ],
      proof: [
        ["Layered diagnosis", "Distinguished valid addressing, routed IP connectivity, name resolution and application-port reachability."],
        ["Shared-scope reasoning", "Used three affected clients to locate a DHCP-distributed DNS configuration error."],
        ["Verification", "Repeated the original tests after the change and confirmed all affected clients."],
      ],
      limits: [
        "Topology, addresses, users, command output and timestamps are synthetic.",
        "The private and reserved domains do not identify a real network or organization.",
        "No production router, DHCP scope, DNS server or firewall was accessed."],
      references: [
        ["IETF RFC 2132 · DHCP domain name server option", "https://www.rfc-editor.org/rfc/rfc2132.html#section-3.8"],
        ["IETF RFC 2606 · Reserved .test domain", "https://www.rfc-editor.org/rfc/rfc2606.html"],
        ["Microsoft Learn · Troubleshooting DNS clients", "https://learn.microsoft.com/en-us/windows-server/networking/dns/troubleshoot/troubleshoot-dns-client"],
        ["Microsoft Learn · nslookup", "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup"],
      ],
    },
  },
};

const fr = {
  "access-restored": {
    ...en["access-restored"],
    tag: "Simulation indépendante de soutien TI",
    plainTitle: "Accès rétabli",
    title: "Accès *rétabli*",
    subtitle: "Labo de soutien aux accès Windows 11 et Microsoft 365",
    lead: "Une panne d’authentification urgente est isolée entre l’utilisateur, l’appareil, l’application et le réseau—sans réinitialiser les identifiants au hasard ni prétendre à un accès au locataire.",
    facts: {
      role: "Analyste de centre de services N1 · simulation",
      type: "Labo de dépannage fondé sur un scénario",
      environment: "MV Windows 11 Pro · parcours de connexion Microsoft 365",
      tools: "PowerShell · Windows Time · Observateur d’événements · billet",
      status: "Simulation documentée · aucun locataire Microsoft réel",
      delivered: "Billet · commandes · validation · message utilisateur · note de transmission",
    },
    snapshot: {
      problem: "Après un changement de mot de passe, Outlook et Teams redemandaient la connexion alors que Windows s’ouvrait encore avec les identifiants en cache.",
      user: "Une personne en télétravail pouvait ouvrir l’appareil, mais pas les outils de communication requis pour son quart du matin.",
      result: "Un décalage de huit minutes de l’horloge a été isolé et corrigé; le parcours d’authentification a ensuite réussi tous les contrôles simulés.",
    },
    preview: {
      ...en["access-restored"].preview,
      eyebrow: "Enquête sur l’accès",
      status: "Résolu",
      headline: "Boucle de connexion Microsoft 365",
      detail: "Un utilisateur · Windows 11 · à distance",
      nodes: [
        { label: "Utilisateur", value: "Mot de passe modifié", state: "clear" },
        { label: "Appareil", value: "+08:14", state: "fault" },
        { label: "Application", value: "Jeton refusé", state: "review" },
        { label: "Réseau", value: "TCP 443 accessible", state: "clear" },
      ],
    },
    context: {
      ...en["access-restored"].context,
      number: "01 — Incident et portée",
      heading: "Une invite de connexion peut venir de bien plus loin que le mot de passe.",
      prose: [
        "Le signalement est arrivé à 8 h 17 après un changement de mot de passe la veille. Windows 11 s’ouvrait encore, mais Outlook et Teams demandaient continuellement une authentification. Une collègue utilisant le même service n’était pas touchée.",
        "L’objectif était de rétablir l’accès avec l’action sûre la moins intrusive. L’enquête a donc séparé le compte, l’appareil, l’application, la connectivité et l’état du service.",
      ],
      ticket: {
        ...en["access-restored"].context.ticket,
        status: "Élevé · un utilisateur",
        title: "Outlook et Teams redemandent la connexion après le changement de mot de passe",
        fields: [["Reçu", "8 h 17 HEC"], ["Canal", "Portail de services"], ["Touché", "1 utilisateur / 1 appareil"], ["Impact", "Communications du matin bloquées"], ["Dernier bon état", "Veille · 17 h 40"], ["Changement récent", "Mot de passe modifié"]],
      },
      scope: [
        { term: "Preuves contrôlées", desc: "Les vérifications Windows, les commandes, les horaires et l’historique utilisent des données synthétiques." },
        { term: "Aucune administration du locataire", desc: "Aucune stratégie Entra ID, accès conditionnel, licence ou Intune n’a été modifiée; ce sont des voies de transmission explicites." },
        { term: "Limite de sécurité", desc: "La procédure ne demande jamais le mot de passe, l’approbation d’une MFA inattendue ni la désactivation d’un contrôle de sécurité." },
      ],
    },
    investigation: {
      ...en["access-restored"].investigation,
      number: "02 — Enquête",
      heading: "Tester le parcours par couches; une variable à la fois.",
      prose: [
        "Les preuves ont écarté une panne générale de Microsoft 365 et un problème de connectivité de base avant toute action sur les identifiants. La comparaison de l’heure de l’appareil avec une source fiable a révélé la première anomalie.",
        "Windows Time fonctionnait, mais l’instantané restauré de la MV ne s’était pas resynchronisé. Les jetons étant liés au temps, l’horloge est devenue l’hypothèse locale la plus forte.",
      ],
      trail: [
        { time: "8 h 20", title: "Portée confirmée", evidence: "Un utilisateur et un appareil Windows 11; collègue non touchée.", result: "Traiter comme un incident local ou propre au compte.", state: "clear" },
        { time: "8 h 24", title: "Service et réseau vérifiés", evidence: "Parcours Microsoft 365 supposé disponible; TCP 443 vers login.microsoftonline.com réussi.", result: "La joignabilité de base n’est pas le point de rupture.", state: "clear" },
        { time: "8 h 29", title: "Heure comparée", evidence: "L’horloge avançait de 8 minutes 14 secondes.", result: "Le décalage peut invalider l’authentification par jeton.", state: "fault" },
        { time: "8 h 33", title: "Resynchronisation sûre", evidence: "État de Windows Time vérifié, puis resynchronisation demandée sans effacer profil ni identifiants.", result: "Écart ramené à moins d’une seconde.", state: "clear" },
        { time: "8 h 38", title: "Accès validé", evidence: "Navigateur, Outlook et Teams ont réussi les contrôles simulés sans nouvelle invite.", result: "Flux de travail rétabli; billet prêt à fermer.", state: "clear" },
      ],
      artifact: { ...en["access-restored"].investigation.artifact, eyebrow: "Dossier PowerShell · sortie synthétique", title: "Peu de commandes, chacune liée à une question", note: "Les sorties sont synthétiques et ne révèlent aucun utilisateur, locataire ni appareil réel.", rows: [["Décalage", "+00:08:14", "Hors tolérance attendue; vérifier la synchronisation."], ["Windows Time", "En cours", "La source et la dernière synchronisation comptent aussi."], ["TCP 443", "Accessible", "Le point de connexion répond; cela ne valide pas les identifiants."], ["Portée", "1 appareil", "Garder l’enquête locale tant qu’aucune preuve ne montre un impact plus large."]] },
      decisions: [
        { name: "Ne pas réinitialiser le mot de passe deux fois", problem: "Un changement récent rend une seconde réinitialisation tentante, mais elle peut ajouter blocages et confusion de cache.", decision: "Vérifier portée, heure, réseau et navigateur avant de modifier l’identité.", tradeoff: "Quelques minutes de diagnostic pour éviter une action sensible inutile." },
        { name: "Utiliser le navigateur comme étape d’isolement", problem: "Les clients de bureau ajoutent cache, profils et extensions.", decision: "Comparer la connexion Web à Outlook et Teams après les contrôles d’heure et de réseau.", tradeoff: "Cela ne corrige pas le client, mais sépare le compte de l’état local." },
        { name: "Transmettre les preuves de stratégie et de conformité", problem: "Le N1 ne doit pas deviner l’accès conditionnel, la licence ou la conformité.", decision: "Joindre horaires, impact et contrôles locaux pour l’administrateur Microsoft 365 ou identité.", tradeoff: "Un autre responsable peut être requis, mais la transmission est exploitable." },
      ],
    },
    resolution: {
      ...en["access-restored"].resolution,
      number: "03 — Résolution et validation",
      heading: "Rétablir l’heure fiable, puis prouver que l’utilisateur peut travailler.",
      prose: ["L’action simulée a resynchronisé Windows Time. Aucun profil n’a été supprimé, aucun mot de passe exposé et aucune stratégie contournée.", "La fermeture exigeait plus qu’une commande réussie : l’heure, le navigateur et les deux applications touchées ont été validés dans l’ordre utile à l’utilisateur."],
      validation: [["Écart d’horloge", "Moins d’une seconde", "done"], ["Connexion Web", "Terminée", "done"], ["Outlook", "Boîte ouverte", "done"], ["Teams", "Session connectée", "done"]],
      communication: { label: "Mise à jour · 8 h 40 HEC", text: "L’accès est rétabli. L’horloge de l’appareil n’était plus synchronisée, ce qui interrompait l’authentification Microsoft 365. J’ai resynchronisé Windows Time et validé avec vous le navigateur, Outlook et Teams. Aucun nouveau changement de mot de passe n’a été nécessaire." },
      escalation: "Transmettre l’heure de connexion, l’identifiant utilisateur, l’appareil et les contrôles locaux si la MFA, la licence, l’accès conditionnel, les journaux Entra ou la conformité Intune restent en cause. Ne jamais demander d’image exposant jeton, mot de passe ou code de récupération.",
    },
    prevention: {
      ...en["access-restored"].prevention,
      number: "04 — Prévention et réutilisation",
      heading: "Transformer une résolution en première réponse plus sûre.",
      prose: ["La sortie réutilisable est une courte procédure qui commence par l’impact et la portée, puis progresse de l’observation sans risque vers la transmission au niveau du compte.", "Dans un environnement géré, un décalage récurrent doit devenir un signal de gestion des terminaux, pas une correction répétée appareil par appareil."],
      runbook: ["Confirmer utilisateur, appareil, applications, erreur exacte et changements récents.", "Vérifier l’état du service et si une autre personne ou un autre appareil est touché.", "Vérifier date, heure, fuseau, source Windows Time et joignabilité.", "Comparer navigateur et clients sans supprimer les profils trop tôt.", "Résoudre dans la portée ou transmettre identité, licence et conformité au bon responsable.", "Valider le vrai flux de travail et documenter cause, action et prochaine étape."],
      measures: [["Incidents répétés par cause", "Montre si heure, cache, MFA ou stratégie mérite une correction permanente."], ["Résolution au premier contact", "Montre si le N1 rétablit l’accès sans raccourci risqué."], ["Taux de réouverture à sept jours", "Montre si la validation reflétait le travail réel."]],
    },
    outcome: {
      ...en["access-restored"].outcome,
      number: "05 — Preuves et limites",
      heading: "Un dossier complet, pas une prétention d’administration en production.",
      prose: ["Ce cas démontre une enquête N1 structurée, une communication consciente de la sécurité et une transmission fondée sur les preuves. Il ne prétend ni à la gestion d’un locataire Microsoft ni à un résultat commercial mesuré."],
      proof: [["Dépannage", "Séparation des couches identité, appareil, application, réseau et service."], ["Communication technique", "Transformation des commandes en mise à jour et note de fermeture concises."], ["Jugement opérationnel", "Action sûre la moins invasive et responsabilité suivante clairement définie."]],
      limits: ["Scénario, horaires, noms et sorties synthétiques.", "Aucun locataire Microsoft 365, répertoire Entra ID ni stratégie Intune réel n’a été consulté.", "Le résultat simulé n’est pas présenté comme performance client ou SLA."],
    },
  },

  "missing-reservation": {
    ...en["missing-reservation"],
    tag: "Simulation indépendante de soutien applicatif",
    plainTitle: "La réservation manquante",
    title: "La réservation *manquante*",
    subtitle: "Soutien applicatif SaaS — API, webhook, journaux et SQL",
    lead: "Une réservation acceptée par une API n’apparaît jamais en aval. Un identifiant de corrélation relie le signalement au payload, au webhook, à la requête SQL en lecture seule et à une résolution exploitable par l’ingénierie.",
    facts: { role: "Analyste junior de soutien applicatif · simulation", type: "Incident synthétique d’intégration", environment: "API de réservation fictive · consommateur webhook · base relationnelle", tools: "Requête type Postman · HTTP/JSON · SQL · journaux · transmission Jira", status: "Scénario reproductible · aucune donnée client ou de production", delivered: "Billet · payload · trace · SQL · validation de reprise · note de base de connaissances" },
    snapshot: { problem: "La source a renvoyé 202 Accepted, mais RSV-8F31C n’est jamais apparue dans le tableau de bord partenaire.", user: "Un agent des opérations ne pouvait pas confirmer si l’arrivée avait atteint le système aval.", result: "Une date au format local a causé le rejet 422 du webhook; l’événement corrigé a créé un seul enregistrement." },
    preview: { ...en["missing-reservation"].preview, eyebrow: "Trace d’intégration", status: "Résolu", headline: "Réservation acceptée, non livrée", detail: "Corrélation · req_9c7f2a", nodes: [{ label: "API", value: "202 accepté", state: "clear" }, { label: "File", value: "evt_7a31", state: "clear" }, { label: "Webhook", value: "422 format de date", state: "fault" }, { label: "Base", value: "1 ligne après reprise", state: "clear" }] },
    context: {
      ...en["missing-reservation"].context, number: "01 — Incident et portée", heading: "Accepté ne veut pas dire livré.",
      prose: ["À 14 h 06, une agente a signalé qu’une réservation confirmée dans la source manquait au tableau partenaire. Une saisie manuelle pouvait créer un doublon; il fallait donc établir l’état de l’événement avant toute modification.", "Le scénario utilise un flux fictif inspiré d’opérations de service courantes. Chaque client, identifiant, payload et journal est synthétique; aucune donnée ICNEA, Salesforce, hôtelière ou client n’est représentée."],
      ticket: { ...en["missing-reservation"].context.ticket, status: "Élevé · arrivée aujourd’hui", title: "Réservation confirmée absente du tableau partenaire", fields: [["Reçu", "14 h 06 HEC"], ["Réservation", "RSV-8F31C"], ["Corrélation", "req_9c7f2a"], ["Événement", "evt_7a31"], ["Réponse source", "202 Accepted"], ["Impact", "Arrivée non confirmée en aval"]] },
      scope: [{ term: "Lire avant d’écrire", desc: "Vérifier l’événement et la réservation avant toute reprise ou correction manuelle." }, { term: "Intégration synthétique", desc: "API, webhook, lignes SQL et journaux forment un environnement fictif cohérent." }, { term: "Limite du soutien", desc: "Le soutien valide et documente; toute modification permanente de code ou de mapping appartient à l’ingénierie." }],
    },
    investigation: {
      ...en["missing-reservation"].investigation, number: "02 — Enquête", heading: "Suivre un identifiant de corrélation à chaque transfert.",
      prose: ["Le 202 prouvait seulement que la source avait accepté un traitement asynchrone. La corrélation a relié la requête à evt_7a31 et à une réponse aval 422.", "Le webhook exigeait une date ISO 8601. Le payload contenait 23/09/2026. Une requête SQL en lecture seule a confirmé trois échecs et aucune réservation aval."],
      trail: [{ time: "14 h 09", title: "Doublon évité", evidence: "Aucune nouvelle saisie; identifiants capturés d’abord.", result: "Préserver l’idempotence tant que la livraison est inconnue.", state: "clear" }, { time: "14 h 13", title: "Acceptation source vérifiée", evidence: "POST = 202, req_9c7f2a et evt_7a31.", result: "Entré dans le parcours asynchrone; livraison non prouvée.", state: "clear" }, { time: "14 h 18", title: "Échec du webhook tracé", evidence: "HTTP 422 : check_in doit être YYYY-MM-DD.", result: "La validation bloque la création aval.", state: "fault" }, { time: "14 h 23", title: "État stocké vérifié", evidence: "Événement failed, trois reprises; zéro réservation.", result: "Une reprise contrôlée est sûre après correction.", state: "clear" }, { time: "14 h 31", title: "Reprise validée", evidence: "Payload corrigé = 200; deuxième reprise sans doublon.", result: "Une seule réservation livrée.", state: "clear" }],
      artifact: { ...en["missing-reservation"].investigation.artifact, eyebrow: "HTTP, JSON et SQL · données synthétiques", title: "L’échec apparaît dans le contrat et l’état stocké", note: "Les identifiants sont fictifs. La requête en lecture seule est limitée à l’événement et à la réservation du billet.", rows: [["Réponse source", "202 Accepted", "Tâche mise en file; non terminée en aval."], ["check_in", "23/09/2026", "Date locale incompatible avec le contrat."], ["Webhook", "422", "Requête comprise mais données rejetées."], ["Lignes réservation", "0 avant / 1 après", "La reprise contrôlée n’a créé aucun doublon."]] },
      decisions: [{ name: "Ne pas transformer 202 en succès", problem: "Une API asynchrone accepte avant la fin en aval.", decision: "Suivre événement et corrélation dans la file, le webhook et la base.", tradeoff: "Plus d’enquête, mais une conclusion défendable." }, { name: "Limiter la requête à l’incident", problem: "Une requête large augmente le risque et le bruit.", decision: "Lecture seule limitée aux deux identifiants du billet.", tradeoff: "Moins de contexte exploratoire, mais plus sûr et reproductible." }, { name: "Reprendre avec contrôle d’idempotence", problem: "Une nouvelle tentative peut dupliquer une réservation.", decision: "Confirmer zéro ligne, corriger, reprendre une fois, puis tester la même clé.", tradeoff: "Validation supplémentaire pour protéger l’intégrité." }],
    },
    resolution: {
      ...en["missing-reservation"].resolution, number: "03 — Résolution et validation", heading: "Corriger le contrat, puis valider l’état—pas seulement HTTP.",
      prose: ["Le correctif de laboratoire a changé check_in pour 2026-09-23 et rejoué evt_7a31 avec la clé d’idempotence d’origine. Le consommateur a renvoyé 200 processed.", "Une seconde reprise a renvoyé le résultat existant et la base contenait toujours une seule réservation."],
      validation: [["Webhook", "200 processed", "done"], ["Événement", "processed", "done"], ["Réservations", "exactement 1", "done"], ["Deuxième reprise", "aucun doublon", "done"]],
      communication: { label: "Mise à jour · 14 h 34 HEC", text: "La réservation avait atteint le système source, mais sa validation en aval a échoué parce qu’une date utilisait un format d’affichage local. L’événement corrigé a été traité et j’ai confirmé qu’une seule réservation existe dans l’enregistrement partenaire. Aucune saisie manuelle n’est nécessaire." },
      escalation: "La transmission de production comprendrait payload nettoyé, schéma attendu, identifiants, heures UTC, réponse 422, nombre de reprises, SQL limité, reproduction et impact. L’ingénierie possède le correctif permanent; le soutien conserve le fil client jusqu’à confirmation.",
    },
    prevention: {
      ...en["missing-reservation"].prevention, number: "04 — Prévention et réutilisation", heading: "Faire échouer la prochaine erreur de format plus tôt et plus clairement.",
      prose: ["Le correctif immédiat restaure un événement. La prévention appartient à la validation de contrat, aux tests de mapping, aux journaux exploitables et à une procédure qui distingue accepté, en file, livré et échoué.", "Un motif 422 récurrent doit être résumé pour Produit et Ingénierie, pas normalisé comme travail manuel."],
      runbook: ["Capturer impact, identifiant métier, heure et premier système où l’objet apparaît.", "Noter corrélation, requête et événement avant toute reprise.", "Séparer succès du transport et traitement métier aval.", "Examiner payloads nettoyés, journaux et état en lecture seule.", "Vérifier idempotence et lignes avant une reprise contrôlée.", "Valider le résultat visible et transmettre les changements permanents avec toutes les preuves."],
      measures: [["Échecs webhook par statut et champ", "Révèle quel mapping, client ou contrat crée le travail répété."], ["Délai accepté-vers-livré", "Sépare l’accusé rapide de la disponibilité réelle."], ["Prévention des doublons", "Confirme que la reprise protège l’intégrité."]],
    },
    outcome: {
      ...en["missing-reservation"].outcome, number: "05 — Preuves et limites", heading: "Le raisonnement du soutien entre le client et l’ingénierie.",
      prose: ["Ce cas montre comment un soutien applicatif junior passe d’un signalement à une transmission reproductible et fondée sur les preuves, sans prétendre posséder le code ou les données de production."],
      proof: [["Raisonnement API", "Différenciation entre acceptation asynchrone, livraison et réponse 422."], ["Contrôle des données", "Requête en lecture seule limitée et validation d’une seule ligne."], ["Qualité de transmission", "Lien entre impact, payload, journaux, identifiants, reproduction et comportement attendu."]],
      limits: ["Entreprise, systèmes, réservation, payloads, journaux et heures fictifs.", "Aucune donnée ICNEA, Salesforce, hôtelière ou client utilisée ou suggérée.", "Le scénario démontre la logique, pas un accès API ou SQL de production."],
    },
  },

  "connectivity-broke": {
    ...en["connectivity-broke"],
    tag: "Simulation indépendante de soutien réseau",
    plainTitle: "Là où la connectivité a rompu",
    title: "Là où la connectivité a *rompu*",
    subtitle: "Dépannage réseau N1 — TCP/IP, DNS et DHCP",
    lead: "Trois clients Windows atteignent la passerelle et une IP publique, mais pas un service interne par son nom. Des tests par couche isolent une ancienne adresse DNS distribuée par DHCP.",
    facts: { role: "Analyste de soutien TI N1 · simulation", type: "Labo de dépannage réseau fondé sur un scénario", environment: "3 clients Windows · modèle LAN/VLAN · DHCP · DNS interne", tools: "ipconfig · ping · nslookup · tracert · Test-NetConnection", status: "Topologie documentée · aucun réseau de production", delivered: "Billet · topologie · commandes · correction · validation · procédure" },
    snapshot: { problem: "Les utilisateurs atteignaient la passerelle et 1.1.1.1, mais portal.supportlab.test échouait par nom sur trois clients DHCP.", user: "Une équipe d’accueil ne pouvait plus ouvrir le portail interne malgré une connectivité IP générale disponible.", result: "L’option DHCP 6 pointait vers un ancien DNS; les clients ont renouvelé le bail corrigé et la résolution est revenue." },
    preview: { ...en["connectivity-broke"].preview, eyebrow: "Parcours de connectivité", status: "Résolu", headline: "Le nom échoue; le chemin IP fonctionne", detail: "3 clients · VLAN 10", nodes: [{ label: "Client", value: "192.168.10.42", state: "clear" }, { label: "Passerelle", value: "192.168.10.1", state: "clear" }, { label: "DNS", value: "192.168.10.53", state: "fault" }, { label: "Portail", value: "192.168.20.25:443", state: "review" }] },
    context: {
      ...en["connectivity-broke"].context, number: "01 — Incident et portée", heading: "« Le réseau est en panne » est un symptôme, pas un diagnostic.",
      prose: ["À 9 h 12, l’accueil a signalé que le portail interne ne s’ouvrait plus. Trois clients Windows montraient la même erreur, tandis que d’autres applications semblaient normales. La portée suggérait une configuration commune.", "Le parcours a testé séparément l’adressage, la passerelle, une IP externe, la résolution de nom et le port de destination."],
      ticket: { ...en["connectivity-broke"].context.ticket, status: "Élevé · 3 utilisateurs", title: "Portail interne indisponible par nom sur le LAN de l’accueil", fields: [["Reçu", "9 h 12 HEC"], ["Touché", "3 clients / VLAN 10"], ["Nom", "portal.supportlab.test"], ["IP client", "192.168.10.42/24"], ["Passerelle", "192.168.10.1"], ["DNS DHCP", "192.168.10.53"]] },
      scope: [{ term: "Topologie modélisée", desc: "Les adresses utilisent des plages privées de labo et n’identifient aucun réseau réel." }, { term: "Une couche par test", desc: "Lien, adressage, passerelle, routage, DNS et port sont évalués séparément." }, { term: "Limite de changement N1", desc: "La correction DHCP est documentée; en production, elle peut appartenir à Réseau ou Infrastructure." }],
    },
    investigation: {
      ...en["connectivity-broke"].investigation, number: "02 — Enquête", heading: "Prouver ce qui fonctionne avant de corriger ce qui ne fonctionne pas.",
      prose: ["Le client avait une adresse privée, un masque et une passerelle valides : ce n’était ni APIPA ni un bail manquant. Les réponses de la passerelle et de 1.1.1.1 prouvaient la connectivité IP locale et routée.", "nslookup expirait contre 192.168.10.53. La comparaison avec la topologie montrait que l’option 6 distribuait encore un DNS retiré; le résolveur actif était 192.168.10.10."],
      trail: [{ time: "9 h 15", title: "Portée commune confirmée", evidence: "Trois clients DHCP du VLAN 10 échouent sur le même nom.", result: "Prioriser DNS/DHCP partagé.", state: "clear" }, { time: "9 h 18", title: "Adressage vérifié", evidence: "192.168.10.42/24, passerelle .1; aucune adresse 169.254.", result: "Bail utilisable reçu.", state: "clear" }, { time: "9 h 21", title: "Chemin IP testé", evidence: "Passerelle et 1.1.1.1 répondent.", result: "Association et routage de base disponibles.", state: "clear" }, { time: "9 h 24", title: "Résolution isolée", evidence: "nslookup expire contre le DNS DHCP 192.168.10.53.", result: "Défaillance de configuration ou de disponibilité DNS.", state: "fault" }, { time: "9 h 32", title: "Renouvellement validé", evidence: "Option corrigée vers .10; clients renouvellent, résolvent et atteignent TCP 443.", result: "Accès rétabli sur les trois clients.", state: "clear" }],
      artifact: { ...en["connectivity-broke"].investigation.artifact, eyebrow: "Dossier réseau Windows · sortie synthétique", title: "Chaque commande répond à une question différente", note: "La séquence évite d’utiliser ping comme test universel. Chaque résultat réduit la couche en cause.", rows: [["Bail DHCP", "192.168.10.42/24 valide", "L’adressage existe; ce n’est pas APIPA."], ["Passerelle", "4/4 réponses", "Le chemin local vers le routeur fonctionne."], ["IP publique", "4/4 réponses", "Le routage IP fonctionne sans DNS."], ["Serveur DNS", "Délai dépassé à .53", "Le résolveur configuré est retiré ou indisponible."]] },
      decisions: [{ name: "Séparer résolution de nom et connectivité", problem: "Une erreur de navigateur est souvent décrite comme panne totale.", decision: "Comparer passerelle, IP publique, nom et port avant de réinitialiser l’adaptateur.", tradeoff: "Une séquence plus longue, mais un domaine de panne précis." }, { name: "Traiter trois clients comme preuve commune", problem: "Des corrections locales répétées cachent un défaut DHCP.", decision: "Comparer les baux et inspecter la portée partagée.", tradeoff: "Coordination avec Réseau, mais correction à la source." }, { name: "Renouveler après correction de la source", problem: "L’option DHCP modifiée ne met pas à jour immédiatement le bail actif.", decision: "Renouveler, vider le cache puis refaire les mêmes tests.", tradeoff: "Brève interruption pour prouver la réception de la configuration." }],
    },
    resolution: {
      ...en["connectivity-broke"].resolution, number: "03 — Résolution et validation", heading: "Corriger le DNS partagé, puis répéter le parcours initial.",
      prose: ["La portée DHCP modélisée est passée du résolveur retiré 192.168.10.53 au résolveur actif 192.168.10.10. Les clients ont renouvelé leur bail et vidé le cache.", "Les trois ont reçu la bonne adresse DNS, résolu le nom vers 192.168.20.25 et atteint le portail sur TCP 443."],
      validation: [["Option DHCP 6", "192.168.10.10", "done"], ["Résolution", "192.168.20.25", "done"], ["TCP 443", "accessible", "done"], ["Clients touchés", "3 sur 3 rétablis", "done"]],
      communication: { label: "Mise à jour · 9 h 35 HEC", text: "L’accès au portail interne est rétabli sur les trois postes. Les appareils avaient une connectivité valide, mais DHCP fournissait l’adresse d’un ancien serveur DNS. Le paramètre commun a été corrigé, les baux renouvelés et le nom ainsi que le port sécurisé validés. Aucune action utilisateur n’est requise." },
      escalation: "Transmettre si le résolveur actif est indisponible, plusieurs VLAN sont touchés, la portée DHCP dépasse les droits N1, une perte apparaît au-delà de la passerelle ou le nom se résout mais le port reste fermé. Joindre portée, baux, heures, commandes et segment topologique.",
    },
    prevention: {
      ...en["connectivity-broke"].prevention, number: "04 — Prévention et réutilisation", heading: "Éviter que les changements partagés deviennent des incidents découverts par les utilisateurs.",
      prose: ["La procédure transforme un signalement vague en décision répétable. La prévention consiste à intégrer la revue de l’option DHCP et le renouvellement client au retrait d’un DNS.", "Un contrôle synthétique de résolution depuis chaque VLAN important détecterait le résolveur obsolète avant les utilisateurs."],
      runbook: ["Confirmer utilisateurs, segment, type de connexion, nom exact et changements récents.", "Vérifier lien et bail : IP, masque, passerelle, DHCP et DNS.", "Tester passerelle, IP routée, résolution et port séparément.", "Comparer les clients pour localiser DHCP, DNS ou VLAN partagé.", "Corriger dans les droits ou transmettre avec la couche en échec.", "Renouveler, vider le cache, répéter et valider l’application."],
      measures: [["Succès DNS par VLAN", "Détecte un résolveur commun défaillant avant les billets."], ["Renouvellements après changement", "Montre si les clients ont reçu la configuration."], ["Incidents par couche", "Sépare Wi-Fi, DHCP, DNS, routage et service pour prévenir."]],
    },
    outcome: {
      ...en["connectivity-broke"].outcome, number: "05 — Preuves et limites", heading: "Les fondements réseau appliqués comme preuves de soutien.",
      prose: ["Ce cas démontre un raisonnement opérationnel TCP/IP, DHCP et DNS au niveau N1 : assez pour isoler la rupture, rétablir dans la portée ou transmettre les bonnes preuves à Infrastructure."],
      proof: [["Diagnostic par couches", "Différenciation adressage, IP routée, résolution et port applicatif."], ["Raisonnement de portée", "Trois clients ont révélé une erreur DNS distribuée par DHCP."], ["Vérification", "Répétition des tests et confirmation des trois clients après correction."]],
      limits: ["Topologie, adresses, utilisateurs, commandes et heures synthétiques.", "Les domaines privés et réservés n’identifient aucun réseau réel.", "Aucun routeur, DHCP, DNS ou pare-feu de production n’a été consulté."],
    },
  },
};

const collections = { en, fr };

export const CASE_STUDY_SLUGS = ["access-restored", "missing-reservation", "connectivity-broke"];

export function getCaseStudy(lang, slug) {
  const locale = collections[lang] || collections.en;
  const study = locale[slug] || collections.en[slug];
  if (!study) return null;
  return { ...(shared[lang] || shared.en), study };
}

export function getCaseStudyList(lang) {
  return CASE_STUDY_SLUGS.map((slug) => getCaseStudy(lang, slug)?.study).filter(Boolean);
}
